export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
